//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBC.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBC.Models.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new municipality added.
        /// </summary>
        public static string NewMunicipalityAdded {
            get {
                return ResourceManager.GetString("NewMunicipalityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No municipality with the given name exists.
        /// </summary>
        public static string NoMunicipalityWithNameExist {
            get {
                return ResourceManager.GetString("NoMunicipalityWithNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule is registered for this municipality.
        /// </summary>
        public static string NoRuleForMunicipality {
            get {
                return ResourceManager.GetString("NoRuleForMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A municipality with the same name already exists.
        /// </summary>
        public static string SameMunicipalityExist {
            get {
                return ResourceManager.GetString("SameMunicipalityExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tax rule has been added.
        /// </summary>
        public static string TaxRuleAdded {
            get {
                return ResourceManager.GetString("TaxRuleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax rule must at least has one period.
        /// </summary>
        public static string TaxRuleMustHavePeriod {
            get {
                return ResourceManager.GetString("TaxRuleMustHavePeriod", resourceCulture);
            }
        }
    }
}
